name = "RecurrentNetworkAnalysis"
uuid = "2a85ccfc-98a0-47fa-b945-b561fd76af20"
authors = ["Roger Heirkstad <roger.herikstad@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
LinearAlgebra = "1.10.0 - 1.11.0"
Test = "1.10.0 - 1.11.0"
